
batch_size_train = 1
batch_size_train_v2 = 128
batch_size_valid = 256
demand_dict_file = './data/yellow_tripdata_500_10.npy'
dev = 'cuda:0'
# dev = 'cpu'
evaluate_model = true
grid_cell_area = 250000
learning_rate = 0.001
model_name = 'SingleCellFCNNv3PosNotNormalized'
n_epochs = 15
nof_input_maps = 4
nof_neurons_per_layer = [32, 64]
normalized = true
pgc_grid_bl_lat = 40.5879173223792
pgc_grid_bl_lon = -74.08982909538462
pgc_grid_tr_lat = 40.90138693938339
pgc_grid_tr_lon = -73.6856599028536
random_seed = 42
red_b = 26
red_l = 10
red_r = 39
red_t = 24
start = 2015-01-01T00:00:00
end = 2016-07-01T00:00:00
time_bin_size = 10
weight_decay = 0.001
weather_file = '../data/additional_data_weather_nyc_hourly_2015_2016.csv'
X_mean = 11.858476560141144
X_std = 16.399040080276734
